### ISSUE TITLE
Module not found 

### ISSUE THREAD

**Issue by adityanamansingh** [suryadeepti/Invisible-Cloak#1]
`---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-2-a62e8ce05786> in <module>
----> 1 import cv2
      2 import time
      3 import numpy as np
      4 
      5 fourcc= cv2.VideoWriter_fourcc(*'XVID')

ModuleNotFoundError: No module named `'cv2'``

**Comment by yaswanthadimulam** [comment]
Hi Aditya,

https://opencv-python-tutroals.readthedocs.io/en/latest/py_tutorials/py_setup/py_setup_in_windows/py_setup_in_windows.html

i think this might help you ! :)

**Comment by suryadeepti** [comment]
Install OpenCV
